### ISSUE TITLE
let player remember it was in full screen

### ISSUE THREAD

**Issue by legacychimera247** [nate-xyz/resonance#86] opened 2023-04-14 00:09 UTC
everytime i close and open the player again i need to set it in fullscreen again, i guess it should remember it was in full screen, it's aimed at gnome after all :P :P

**Comment by nate-xyz** [comment] 2023-04-14 12:46
Duplicate of https://github.com/nate-xyz/resonance/issues/12

**Closed** 2023-04-15 01:00 UTC
Labels: duplicate
