### ISSUE TITLE
if song titles is too long and you hover the mouse on it the entire album moves slightly

### ISSUE THREAD

**Issue by legacychimera247** [nate-xyz/resonance#81] opened 2023-04-13 12:19 UTC
well, i guess in this case the title says it all, this should be just a little alpha quick :)

an example of what i mean
[Video del 2023-04-13 15-31-47.webm](https://user-images.githubusercontent.com/22254556/231775235-076d4a5c-c74e-4978-bf9d-f2374ff01646.webm)

**Comment by nate-xyz** [comment] 2023-04-13 14:42
Duplicate of https://github.com/nate-xyz/resonance/issues/20
Related to https://github.com/nate-xyz/resonance/issues/28

**Closed** 2023-04-13 22:32 UTC
Labels: bug, duplicate, design
